#!/bin/bash

NAME=fastapi-app
DIR=/home/hostvlg/brastoolbe
USER=hostvlg
GROUP=hostvlg
WORKERS=3
WORKER_CLASS=geventwebsocket.gunicorn.workers.GeventWebSocketWorker
VENV=$DIR/venv/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error

cd $DIR
source $VENV

exec gunicorn index:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-